pub mod app;
pub mod current_song;
mod cover_picture;
pub mod track_list;
pub mod song_object;
mod browse;
pub mod album_object;
mod random_songs_dialog;
pub mod setup;
pub mod preferences_view;
mod lyrics_line;
pub mod bottom_bar;
mod header_bar;
pub mod artist_object;
